### ISSUE TITLE
animation.c doesn't work

### ISSUE THREAD

**Issue by crazyBaboon** [bytebrew/slope#14]
using gcc animation.c -lslope -lm -o simple `pkg-config --cflags --libs gtk+-3.0`, I get the following:

animation.c: In function ‘timer_callback’:
animation.c:42:5: warning: implicit declaration of function ‘slope_chart_redraw’ [-Wimplicit-function-declaration]
     slope_chart_redraw(SLOPE_CHART(chart));
     ^~~~~~~~~~~~~~~~~~
/tmp/ccEnD5Cu.o: In function `timer_callback':
animation.c:(.text+0x146): undefined reference to `slope_chart_redraw'
collect2: error: ld returned 1 exit status

Please see the next merge request for a potential solution, including the now fixed y-axis issue!

**Comment by elvismt** [comment]
I think you compiled this application without updating your installed version of the library. `slope_chart_redraw()` is a new function introduced today. It is a better approach because it only redraws the chart for each frame instead of the whole window. Please recompile slope and them animation.c would work. I checked the version in branch master and it is working. Additionally, please issue your next pull requests on top of the devel branch instead of the master one.

**Comment by crazyBaboon** [comment]
ok thanks i'll give it a go! Also, I have added animation_stack! Have you checked that out?
